
# initializeDatabase
GET http://localhost:8000/api/initializeDatabase
###


# statistics
GET http://localhost:8000/api/statistics/2

###


# barChart

GET http://localhost:8000/api/barChart/1


###


# pieChart
GET http://localhost:8000/api/pieChart/1


###


# combinedData
GET http://localhost:8000/api/combinedData/1

